// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.AttributeHandleValueMap in DataTypes.proto
package fedpro.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

/**
 * Map with AttributeHandle as key.
 * The map shall not contain duplicate keys.
 */
public class AttributeHandleValueMap(
  attributeHandleValue: List<AttributeHandleValue> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AttributeHandleValueMap, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.AttributeHandleValue#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val attributeHandleValue: List<AttributeHandleValue> =
      immutableCopyOf("attributeHandleValue", attributeHandleValue)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AttributeHandleValueMap) return false
    if (unknownFields != other.unknownFields) return false
    if (attributeHandleValue != other.attributeHandleValue) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + attributeHandleValue.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (attributeHandleValue.isNotEmpty()) result +=
        """attributeHandleValue=$attributeHandleValue"""
    return result.joinToString(prefix = "AttributeHandleValueMap{", separator = ", ", postfix = "}")
  }

  public fun copy(attributeHandleValue: List<AttributeHandleValue> = this.attributeHandleValue,
      unknownFields: ByteString = this.unknownFields): AttributeHandleValueMap =
      AttributeHandleValueMap(attributeHandleValue, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AttributeHandleValueMap> = object :
        ProtoAdapter<AttributeHandleValueMap>(
      FieldEncoding.LENGTH_DELIMITED, 
      AttributeHandleValueMap::class, 
      "type.googleapis.com/fedpro.AttributeHandleValueMap", 
      PROTO_3, 
      null, 
      "DataTypes.proto"
    ) {
      override fun encodedSize(`value`: AttributeHandleValueMap): Int {
        var size = value.unknownFields.size
        size += AttributeHandleValue.ADAPTER.asRepeated().encodedSizeWithTag(1,
            value.attributeHandleValue)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AttributeHandleValueMap) {
        AttributeHandleValue.ADAPTER.asRepeated().encodeWithTag(writer, 1,
            value.attributeHandleValue)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AttributeHandleValueMap) {
        writer.writeBytes(value.unknownFields)
        AttributeHandleValue.ADAPTER.asRepeated().encodeWithTag(writer, 1,
            value.attributeHandleValue)
      }

      override fun decode(reader: ProtoReader): AttributeHandleValueMap {
        val attributeHandleValue = mutableListOf<AttributeHandleValue>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> attributeHandleValue.add(AttributeHandleValue.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return AttributeHandleValueMap(
          attributeHandleValue = attributeHandleValue,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AttributeHandleValueMap): AttributeHandleValueMap = value.copy(
        attributeHandleValue =
            value.attributeHandleValue.redactElements(AttributeHandleValue.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
