// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.DimensionHandleSet in DataTypes.proto
package fedpro.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

/**
 * Set of DimensionHandle elements.
 * The set shall not contain duplicate elements.
 */
public class DimensionHandleSet(
  dimensionHandle: List<DimensionHandle> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DimensionHandleSet, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.DimensionHandle#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val dimensionHandle: List<DimensionHandle> = immutableCopyOf("dimensionHandle",
      dimensionHandle)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DimensionHandleSet) return false
    if (unknownFields != other.unknownFields) return false
    if (dimensionHandle != other.dimensionHandle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + dimensionHandle.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (dimensionHandle.isNotEmpty()) result += """dimensionHandle=$dimensionHandle"""
    return result.joinToString(prefix = "DimensionHandleSet{", separator = ", ", postfix = "}")
  }

  public fun copy(dimensionHandle: List<DimensionHandle> = this.dimensionHandle,
      unknownFields: ByteString = this.unknownFields): DimensionHandleSet =
      DimensionHandleSet(dimensionHandle, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DimensionHandleSet> = object :
        ProtoAdapter<DimensionHandleSet>(
      FieldEncoding.LENGTH_DELIMITED, 
      DimensionHandleSet::class, 
      "type.googleapis.com/fedpro.DimensionHandleSet", 
      PROTO_3, 
      null, 
      "DataTypes.proto"
    ) {
      override fun encodedSize(`value`: DimensionHandleSet): Int {
        var size = value.unknownFields.size
        size += DimensionHandle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.dimensionHandle)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DimensionHandleSet) {
        DimensionHandle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.dimensionHandle)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DimensionHandleSet) {
        writer.writeBytes(value.unknownFields)
        DimensionHandle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.dimensionHandle)
      }

      override fun decode(reader: ProtoReader): DimensionHandleSet {
        val dimensionHandle = mutableListOf<DimensionHandle>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> dimensionHandle.add(DimensionHandle.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return DimensionHandleSet(
          dimensionHandle = dimensionHandle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DimensionHandleSet): DimensionHandleSet = value.copy(
        dimensionHandle = value.dimensionHandle.redactElements(DimensionHandle.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
