// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.FederateHandleSet in DataTypes.proto
package fedpro.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

/**
 * Set of FederateHandle elements.
 * The set shall not contain duplicate elements.
 */
public class FederateHandleSet(
  federateHandle: List<FederateHandle> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<FederateHandleSet, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.FederateHandle#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val federateHandle: List<FederateHandle> = immutableCopyOf("federateHandle",
      federateHandle)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FederateHandleSet) return false
    if (unknownFields != other.unknownFields) return false
    if (federateHandle != other.federateHandle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + federateHandle.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (federateHandle.isNotEmpty()) result += """federateHandle=$federateHandle"""
    return result.joinToString(prefix = "FederateHandleSet{", separator = ", ", postfix = "}")
  }

  public fun copy(federateHandle: List<FederateHandle> = this.federateHandle,
      unknownFields: ByteString = this.unknownFields): FederateHandleSet =
      FederateHandleSet(federateHandle, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FederateHandleSet> = object : ProtoAdapter<FederateHandleSet>(
      FieldEncoding.LENGTH_DELIMITED, 
      FederateHandleSet::class, 
      "type.googleapis.com/fedpro.FederateHandleSet", 
      PROTO_3, 
      null, 
      "DataTypes.proto"
    ) {
      override fun encodedSize(`value`: FederateHandleSet): Int {
        var size = value.unknownFields.size
        size += FederateHandle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.federateHandle)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: FederateHandleSet) {
        FederateHandle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.federateHandle)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: FederateHandleSet) {
        writer.writeBytes(value.unknownFields)
        FederateHandle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.federateHandle)
      }

      override fun decode(reader: ProtoReader): FederateHandleSet {
        val federateHandle = mutableListOf<FederateHandle>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> federateHandle.add(FederateHandle.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return FederateHandleSet(
          federateHandle = federateHandle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: FederateHandleSet): FederateHandleSet = value.copy(
        federateHandle = value.federateHandle.redactElements(FederateHandle.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
