// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.RegionHandleSet in DataTypes.proto
package fedpro.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

/**
 * Set of RegionHandle elements.
 * The set shall not contain duplicate elements.
 */
public class RegionHandleSet(
  regionHandle: List<RegionHandle> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RegionHandleSet, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.RegionHandle#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val regionHandle: List<RegionHandle> = immutableCopyOf("regionHandle", regionHandle)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RegionHandleSet) return false
    if (unknownFields != other.unknownFields) return false
    if (regionHandle != other.regionHandle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + regionHandle.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (regionHandle.isNotEmpty()) result += """regionHandle=$regionHandle"""
    return result.joinToString(prefix = "RegionHandleSet{", separator = ", ", postfix = "}")
  }

  public fun copy(regionHandle: List<RegionHandle> = this.regionHandle, unknownFields: ByteString =
      this.unknownFields): RegionHandleSet = RegionHandleSet(regionHandle, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RegionHandleSet> = object : ProtoAdapter<RegionHandleSet>(
      FieldEncoding.LENGTH_DELIMITED, 
      RegionHandleSet::class, 
      "type.googleapis.com/fedpro.RegionHandleSet", 
      PROTO_3, 
      null, 
      "DataTypes.proto"
    ) {
      override fun encodedSize(`value`: RegionHandleSet): Int {
        var size = value.unknownFields.size
        size += RegionHandle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.regionHandle)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RegionHandleSet) {
        RegionHandle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.regionHandle)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RegionHandleSet) {
        writer.writeBytes(value.unknownFields)
        RegionHandle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.regionHandle)
      }

      override fun decode(reader: ProtoReader): RegionHandleSet {
        val regionHandle = mutableListOf<RegionHandle>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> regionHandle.add(RegionHandle.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return RegionHandleSet(
          regionHandle = regionHandle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RegionHandleSet): RegionHandleSet = value.copy(
        regionHandle = value.regionHandle.redactElements(RegionHandle.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
