// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.RestoreFailureReason in DataTypes.proto
package fedpro.type

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class RestoreFailureReason(
  override val `value`: Int,
) : WireEnum {
  RTI_UNABLE_TO_RESTORE(0),
  FEDERATE_REPORTED_FAILURE_DURING_RESTORE(1),
  FEDERATE_RESIGNED_DURING_RESTORE(2),
  RTI_DETECTED_FAILURE_DURING_RESTORE(3),
  RESTORE_ABORTED(4),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RestoreFailureReason> = object :
        EnumAdapter<RestoreFailureReason>(
      RestoreFailureReason::class, 
      PROTO_3, 
      RestoreFailureReason.RTI_UNABLE_TO_RESTORE
    ) {
      override fun fromValue(`value`: Int): RestoreFailureReason? =
          RestoreFailureReason.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): RestoreFailureReason? = when (value) {
      0 -> RTI_UNABLE_TO_RESTORE
      1 -> FEDERATE_REPORTED_FAILURE_DURING_RESTORE
      2 -> FEDERATE_RESIGNED_DURING_RESTORE
      3 -> RTI_DETECTED_FAILURE_DURING_RESTORE
      4 -> RESTORE_ABORTED
      else -> null
    }
  }
}
