// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.SupplementalReceiveInfo in DataTypes.proto
package fedpro.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class SupplementalReceiveInfo(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.FederateHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val producingFederate: FederateHandle? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val conveyedRegionsIsValid: Boolean = false,
  /**
   * optional, only valid if conveyedRegionsIsValid == true
   */
  @field:WireField(
    tag = 3,
    adapter = "fedpro.type.ConveyedRegionSet#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val conveyedRegions: ConveyedRegionSet? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SupplementalReceiveInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SupplementalReceiveInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (producingFederate != other.producingFederate) return false
    if (conveyedRegionsIsValid != other.conveyedRegionsIsValid) return false
    if (conveyedRegions != other.conveyedRegions) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (producingFederate?.hashCode() ?: 0)
      result = result * 37 + conveyedRegionsIsValid.hashCode()
      result = result * 37 + (conveyedRegions?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (producingFederate != null) result += """producingFederate=$producingFederate"""
    result += """conveyedRegionsIsValid=$conveyedRegionsIsValid"""
    if (conveyedRegions != null) result += """conveyedRegions=$conveyedRegions"""
    return result.joinToString(prefix = "SupplementalReceiveInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    producingFederate: FederateHandle? = this.producingFederate,
    conveyedRegionsIsValid: Boolean = this.conveyedRegionsIsValid,
    conveyedRegions: ConveyedRegionSet? = this.conveyedRegions,
    unknownFields: ByteString = this.unknownFields,
  ): SupplementalReceiveInfo = SupplementalReceiveInfo(producingFederate, conveyedRegionsIsValid,
      conveyedRegions, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SupplementalReceiveInfo> = object :
        ProtoAdapter<SupplementalReceiveInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      SupplementalReceiveInfo::class, 
      "type.googleapis.com/fedpro.SupplementalReceiveInfo", 
      PROTO_3, 
      null, 
      "DataTypes.proto"
    ) {
      override fun encodedSize(`value`: SupplementalReceiveInfo): Int {
        var size = value.unknownFields.size
        if (value.producingFederate != null) size += FederateHandle.ADAPTER.encodedSizeWithTag(1,
            value.producingFederate)
        if (value.conveyedRegionsIsValid != false) size += ProtoAdapter.BOOL.encodedSizeWithTag(2,
            value.conveyedRegionsIsValid)
        if (value.conveyedRegions != null) size += ConveyedRegionSet.ADAPTER.encodedSizeWithTag(3,
            value.conveyedRegions)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SupplementalReceiveInfo) {
        if (value.producingFederate != null) FederateHandle.ADAPTER.encodeWithTag(writer, 1,
            value.producingFederate)
        if (value.conveyedRegionsIsValid != false) ProtoAdapter.BOOL.encodeWithTag(writer, 2,
            value.conveyedRegionsIsValid)
        if (value.conveyedRegions != null) ConveyedRegionSet.ADAPTER.encodeWithTag(writer, 3,
            value.conveyedRegions)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SupplementalReceiveInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.conveyedRegions != null) ConveyedRegionSet.ADAPTER.encodeWithTag(writer, 3,
            value.conveyedRegions)
        if (value.conveyedRegionsIsValid != false) ProtoAdapter.BOOL.encodeWithTag(writer, 2,
            value.conveyedRegionsIsValid)
        if (value.producingFederate != null) FederateHandle.ADAPTER.encodeWithTag(writer, 1,
            value.producingFederate)
      }

      override fun decode(reader: ProtoReader): SupplementalReceiveInfo {
        var producingFederate: FederateHandle? = null
        var conveyedRegionsIsValid: Boolean = false
        var conveyedRegions: ConveyedRegionSet? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> producingFederate = FederateHandle.ADAPTER.decode(reader)
            2 -> conveyedRegionsIsValid = ProtoAdapter.BOOL.decode(reader)
            3 -> conveyedRegions = ConveyedRegionSet.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SupplementalReceiveInfo(
          producingFederate = producingFederate,
          conveyedRegionsIsValid = conveyedRegionsIsValid,
          conveyedRegions = conveyedRegions,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SupplementalReceiveInfo): SupplementalReceiveInfo = value.copy(
        producingFederate = value.producingFederate?.let(FederateHandle.ADAPTER::redact),
        conveyedRegions = value.conveyedRegions?.let(ConveyedRegionSet.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
