// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.AnnounceSynchronizationPoint in FederateAmbassador.proto
package fedpro.callback

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class AnnounceSynchronizationPoint(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val synchronizationPointLabel: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val userSuppliedTag: ByteString = ByteString.EMPTY,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AnnounceSynchronizationPoint, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AnnounceSynchronizationPoint) return false
    if (unknownFields != other.unknownFields) return false
    if (synchronizationPointLabel != other.synchronizationPointLabel) return false
    if (userSuppliedTag != other.userSuppliedTag) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + synchronizationPointLabel.hashCode()
      result = result * 37 + userSuppliedTag.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """synchronizationPointLabel=${sanitize(synchronizationPointLabel)}"""
    result += """userSuppliedTag=$userSuppliedTag"""
    return result.joinToString(prefix = "AnnounceSynchronizationPoint{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    synchronizationPointLabel: String = this.synchronizationPointLabel,
    userSuppliedTag: ByteString = this.userSuppliedTag,
    unknownFields: ByteString = this.unknownFields,
  ): AnnounceSynchronizationPoint = AnnounceSynchronizationPoint(synchronizationPointLabel,
      userSuppliedTag, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AnnounceSynchronizationPoint> = object :
        ProtoAdapter<AnnounceSynchronizationPoint>(
      FieldEncoding.LENGTH_DELIMITED, 
      AnnounceSynchronizationPoint::class, 
      "type.googleapis.com/fedpro.AnnounceSynchronizationPoint", 
      PROTO_3, 
      null, 
      "FederateAmbassador.proto"
    ) {
      override fun encodedSize(`value`: AnnounceSynchronizationPoint): Int {
        var size = value.unknownFields.size
        if (value.synchronizationPointLabel != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.synchronizationPointLabel)
        if (value.userSuppliedTag != ByteString.EMPTY) size +=
            ProtoAdapter.BYTES.encodedSizeWithTag(2, value.userSuppliedTag)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AnnounceSynchronizationPoint) {
        if (value.synchronizationPointLabel != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.synchronizationPointLabel)
        if (value.userSuppliedTag != ByteString.EMPTY) ProtoAdapter.BYTES.encodeWithTag(writer, 2,
            value.userSuppliedTag)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AnnounceSynchronizationPoint) {
        writer.writeBytes(value.unknownFields)
        if (value.userSuppliedTag != ByteString.EMPTY) ProtoAdapter.BYTES.encodeWithTag(writer, 2,
            value.userSuppliedTag)
        if (value.synchronizationPointLabel != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.synchronizationPointLabel)
      }

      override fun decode(reader: ProtoReader): AnnounceSynchronizationPoint {
        var synchronizationPointLabel: String = ""
        var userSuppliedTag: ByteString = ByteString.EMPTY
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> synchronizationPointLabel = ProtoAdapter.STRING.decode(reader)
            2 -> userSuppliedTag = ProtoAdapter.BYTES.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return AnnounceSynchronizationPoint(
          synchronizationPointLabel = synchronizationPointLabel,
          userSuppliedTag = userSuppliedTag,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AnnounceSynchronizationPoint): AnnounceSynchronizationPoint =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
