// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.FederateResigned in FederateAmbassador.proto
package fedpro.callback

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class FederateResigned(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val reasonForResignDescription: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<FederateResigned, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FederateResigned) return false
    if (unknownFields != other.unknownFields) return false
    if (reasonForResignDescription != other.reasonForResignDescription) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + reasonForResignDescription.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """reasonForResignDescription=${sanitize(reasonForResignDescription)}"""
    return result.joinToString(prefix = "FederateResigned{", separator = ", ", postfix = "}")
  }

  public fun copy(reasonForResignDescription: String = this.reasonForResignDescription,
      unknownFields: ByteString = this.unknownFields): FederateResigned =
      FederateResigned(reasonForResignDescription, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FederateResigned> = object : ProtoAdapter<FederateResigned>(
      FieldEncoding.LENGTH_DELIMITED, 
      FederateResigned::class, 
      "type.googleapis.com/fedpro.FederateResigned", 
      PROTO_3, 
      null, 
      "FederateAmbassador.proto"
    ) {
      override fun encodedSize(`value`: FederateResigned): Int {
        var size = value.unknownFields.size
        if (value.reasonForResignDescription != "") size +=
            ProtoAdapter.STRING.encodedSizeWithTag(1, value.reasonForResignDescription)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: FederateResigned) {
        if (value.reasonForResignDescription != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.reasonForResignDescription)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: FederateResigned) {
        writer.writeBytes(value.unknownFields)
        if (value.reasonForResignDescription != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.reasonForResignDescription)
      }

      override fun decode(reader: ProtoReader): FederateResigned {
        var reasonForResignDescription: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> reasonForResignDescription = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return FederateResigned(
          reasonForResignDescription = reasonForResignDescription,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: FederateResigned): FederateResigned = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
