// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.InitiateFederateRestore in FederateAmbassador.proto
package fedpro.callback

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import fedpro.type.FederateHandle
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class InitiateFederateRestore(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val label: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val federateName: String = "",
  @field:WireField(
    tag = 3,
    adapter = "fedpro.type.FederateHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val federateHandle: FederateHandle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<InitiateFederateRestore, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is InitiateFederateRestore) return false
    if (unknownFields != other.unknownFields) return false
    if (label != other.label) return false
    if (federateName != other.federateName) return false
    if (federateHandle != other.federateHandle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + label.hashCode()
      result = result * 37 + federateName.hashCode()
      result = result * 37 + (federateHandle?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """label=${sanitize(label)}"""
    result += """federateName=${sanitize(federateName)}"""
    if (federateHandle != null) result += """federateHandle=$federateHandle"""
    return result.joinToString(prefix = "InitiateFederateRestore{", separator = ", ", postfix = "}")
  }

  public fun copy(
    label: String = this.label,
    federateName: String = this.federateName,
    federateHandle: FederateHandle? = this.federateHandle,
    unknownFields: ByteString = this.unknownFields,
  ): InitiateFederateRestore = InitiateFederateRestore(label, federateName, federateHandle,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<InitiateFederateRestore> = object :
        ProtoAdapter<InitiateFederateRestore>(
      FieldEncoding.LENGTH_DELIMITED, 
      InitiateFederateRestore::class, 
      "type.googleapis.com/fedpro.InitiateFederateRestore", 
      PROTO_3, 
      null, 
      "FederateAmbassador.proto"
    ) {
      override fun encodedSize(`value`: InitiateFederateRestore): Int {
        var size = value.unknownFields.size
        if (value.label != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.label)
        if (value.federateName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.federateName)
        if (value.federateHandle != null) size += FederateHandle.ADAPTER.encodedSizeWithTag(3,
            value.federateHandle)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: InitiateFederateRestore) {
        if (value.label != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.label)
        if (value.federateName != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.federateName)
        if (value.federateHandle != null) FederateHandle.ADAPTER.encodeWithTag(writer, 3,
            value.federateHandle)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: InitiateFederateRestore) {
        writer.writeBytes(value.unknownFields)
        if (value.federateHandle != null) FederateHandle.ADAPTER.encodeWithTag(writer, 3,
            value.federateHandle)
        if (value.federateName != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.federateName)
        if (value.label != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.label)
      }

      override fun decode(reader: ProtoReader): InitiateFederateRestore {
        var label: String = ""
        var federateName: String = ""
        var federateHandle: FederateHandle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> label = ProtoAdapter.STRING.decode(reader)
            2 -> federateName = ProtoAdapter.STRING.decode(reader)
            3 -> federateHandle = FederateHandle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return InitiateFederateRestore(
          label = label,
          federateName = federateName,
          federateHandle = federateHandle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: InitiateFederateRestore): InitiateFederateRestore = value.copy(
        federateHandle = value.federateHandle?.let(FederateHandle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
