// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.InitiateFederateSaveWithTime in FederateAmbassador.proto
package fedpro.callback

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import fedpro.type.LogicalTime
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class InitiateFederateSaveWithTime(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val label: String = "",
  @field:WireField(
    tag = 2,
    adapter = "fedpro.type.LogicalTime#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val time: LogicalTime? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<InitiateFederateSaveWithTime, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is InitiateFederateSaveWithTime) return false
    if (unknownFields != other.unknownFields) return false
    if (label != other.label) return false
    if (time != other.time) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + label.hashCode()
      result = result * 37 + (time?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """label=${sanitize(label)}"""
    if (time != null) result += """time=$time"""
    return result.joinToString(prefix = "InitiateFederateSaveWithTime{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    label: String = this.label,
    time: LogicalTime? = this.time,
    unknownFields: ByteString = this.unknownFields,
  ): InitiateFederateSaveWithTime = InitiateFederateSaveWithTime(label, time, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<InitiateFederateSaveWithTime> = object :
        ProtoAdapter<InitiateFederateSaveWithTime>(
      FieldEncoding.LENGTH_DELIMITED, 
      InitiateFederateSaveWithTime::class, 
      "type.googleapis.com/fedpro.InitiateFederateSaveWithTime", 
      PROTO_3, 
      null, 
      "FederateAmbassador.proto"
    ) {
      override fun encodedSize(`value`: InitiateFederateSaveWithTime): Int {
        var size = value.unknownFields.size
        if (value.label != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.label)
        if (value.time != null) size += LogicalTime.ADAPTER.encodedSizeWithTag(2, value.time)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: InitiateFederateSaveWithTime) {
        if (value.label != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.label)
        if (value.time != null) LogicalTime.ADAPTER.encodeWithTag(writer, 2, value.time)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: InitiateFederateSaveWithTime) {
        writer.writeBytes(value.unknownFields)
        if (value.time != null) LogicalTime.ADAPTER.encodeWithTag(writer, 2, value.time)
        if (value.label != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.label)
      }

      override fun decode(reader: ProtoReader): InitiateFederateSaveWithTime {
        var label: String = ""
        var time: LogicalTime? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> label = ProtoAdapter.STRING.decode(reader)
            2 -> time = LogicalTime.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return InitiateFederateSaveWithTime(
          label = label,
          time = time,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: InitiateFederateSaveWithTime): InitiateFederateSaveWithTime =
          value.copy(
        time = value.time?.let(LogicalTime.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
