// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.CreateFederationExecutionWithModulesRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import fedpro.type.FomModuleSet
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class CreateFederationExecutionWithModulesRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val federationExecutionName: String = "",
  @field:WireField(
    tag = 2,
    adapter = "fedpro.type.FomModuleSet#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val fomModules: FomModuleSet? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<CreateFederationExecutionWithModulesRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CreateFederationExecutionWithModulesRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (federationExecutionName != other.federationExecutionName) return false
    if (fomModules != other.fomModules) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + federationExecutionName.hashCode()
      result = result * 37 + (fomModules?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """federationExecutionName=${sanitize(federationExecutionName)}"""
    if (fomModules != null) result += """fomModules=$fomModules"""
    return result.joinToString(prefix = "CreateFederationExecutionWithModulesRequest{", separator =
        ", ", postfix = "}")
  }

  public fun copy(
    federationExecutionName: String = this.federationExecutionName,
    fomModules: FomModuleSet? = this.fomModules,
    unknownFields: ByteString = this.unknownFields,
  ): CreateFederationExecutionWithModulesRequest =
      CreateFederationExecutionWithModulesRequest(federationExecutionName, fomModules,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CreateFederationExecutionWithModulesRequest> = object :
        ProtoAdapter<CreateFederationExecutionWithModulesRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      CreateFederationExecutionWithModulesRequest::class, 
      "type.googleapis.com/fedpro.CreateFederationExecutionWithModulesRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: CreateFederationExecutionWithModulesRequest): Int {
        var size = value.unknownFields.size
        if (value.federationExecutionName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.federationExecutionName)
        if (value.fomModules != null) size += FomModuleSet.ADAPTER.encodedSizeWithTag(2,
            value.fomModules)
        return size
      }

      override fun encode(writer: ProtoWriter,
          `value`: CreateFederationExecutionWithModulesRequest) {
        if (value.federationExecutionName != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.federationExecutionName)
        if (value.fomModules != null) FomModuleSet.ADAPTER.encodeWithTag(writer, 2,
            value.fomModules)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter,
          `value`: CreateFederationExecutionWithModulesRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.fomModules != null) FomModuleSet.ADAPTER.encodeWithTag(writer, 2,
            value.fomModules)
        if (value.federationExecutionName != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.federationExecutionName)
      }

      override fun decode(reader: ProtoReader): CreateFederationExecutionWithModulesRequest {
        var federationExecutionName: String = ""
        var fomModules: FomModuleSet? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> federationExecutionName = ProtoAdapter.STRING.decode(reader)
            2 -> fomModules = FomModuleSet.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CreateFederationExecutionWithModulesRequest(
          federationExecutionName = federationExecutionName,
          fomModules = fomModules,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CreateFederationExecutionWithModulesRequest):
          CreateFederationExecutionWithModulesRequest = value.copy(
        fomModules = value.fomModules?.let(FomModuleSet.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
