// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.GetAvailableDimensionsForInteractionClassRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.InteractionClassHandle
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class GetAvailableDimensionsForInteractionClassRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.InteractionClassHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val theHandle: InteractionClassHandle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetAvailableDimensionsForInteractionClassRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetAvailableDimensionsForInteractionClassRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (theHandle != other.theHandle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (theHandle?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (theHandle != null) result += """theHandle=$theHandle"""
    return result.joinToString(prefix = "GetAvailableDimensionsForInteractionClassRequest{",
        separator = ", ", postfix = "}")
  }

  public fun copy(theHandle: InteractionClassHandle? = this.theHandle, unknownFields: ByteString =
      this.unknownFields): GetAvailableDimensionsForInteractionClassRequest =
      GetAvailableDimensionsForInteractionClassRequest(theHandle, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetAvailableDimensionsForInteractionClassRequest> = object :
        ProtoAdapter<GetAvailableDimensionsForInteractionClassRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetAvailableDimensionsForInteractionClassRequest::class, 
      "type.googleapis.com/fedpro.GetAvailableDimensionsForInteractionClassRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: GetAvailableDimensionsForInteractionClassRequest): Int {
        var size = value.unknownFields.size
        if (value.theHandle != null) size += InteractionClassHandle.ADAPTER.encodedSizeWithTag(1,
            value.theHandle)
        return size
      }

      override fun encode(writer: ProtoWriter,
          `value`: GetAvailableDimensionsForInteractionClassRequest) {
        if (value.theHandle != null) InteractionClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theHandle)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter,
          `value`: GetAvailableDimensionsForInteractionClassRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.theHandle != null) InteractionClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theHandle)
      }

      override fun decode(reader: ProtoReader): GetAvailableDimensionsForInteractionClassRequest {
        var theHandle: InteractionClassHandle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> theHandle = InteractionClassHandle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetAvailableDimensionsForInteractionClassRequest(
          theHandle = theHandle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetAvailableDimensionsForInteractionClassRequest):
          GetAvailableDimensionsForInteractionClassRequest = value.copy(
        theHandle = value.theHandle?.let(InteractionClassHandle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
