// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.GetDimensionUpperBoundRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.DimensionHandle
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class GetDimensionUpperBoundRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.DimensionHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val theHandle: DimensionHandle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetDimensionUpperBoundRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetDimensionUpperBoundRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (theHandle != other.theHandle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (theHandle?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (theHandle != null) result += """theHandle=$theHandle"""
    return result.joinToString(prefix = "GetDimensionUpperBoundRequest{", separator = ", ", postfix
        = "}")
  }

  public fun copy(theHandle: DimensionHandle? = this.theHandle, unknownFields: ByteString =
      this.unknownFields): GetDimensionUpperBoundRequest = GetDimensionUpperBoundRequest(theHandle,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetDimensionUpperBoundRequest> = object :
        ProtoAdapter<GetDimensionUpperBoundRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetDimensionUpperBoundRequest::class, 
      "type.googleapis.com/fedpro.GetDimensionUpperBoundRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: GetDimensionUpperBoundRequest): Int {
        var size = value.unknownFields.size
        if (value.theHandle != null) size += DimensionHandle.ADAPTER.encodedSizeWithTag(1,
            value.theHandle)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetDimensionUpperBoundRequest) {
        if (value.theHandle != null) DimensionHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theHandle)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetDimensionUpperBoundRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.theHandle != null) DimensionHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theHandle)
      }

      override fun decode(reader: ProtoReader): GetDimensionUpperBoundRequest {
        var theHandle: DimensionHandle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> theHandle = DimensionHandle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetDimensionUpperBoundRequest(
          theHandle = theHandle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetDimensionUpperBoundRequest): GetDimensionUpperBoundRequest =
          value.copy(
        theHandle = value.theHandle?.let(DimensionHandle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
