// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.GetUpdateRateValueRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class GetUpdateRateValueRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val updateRateDesignator: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetUpdateRateValueRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetUpdateRateValueRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (updateRateDesignator != other.updateRateDesignator) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + updateRateDesignator.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """updateRateDesignator=${sanitize(updateRateDesignator)}"""
    return result.joinToString(prefix = "GetUpdateRateValueRequest{", separator = ", ", postfix =
        "}")
  }

  public fun copy(updateRateDesignator: String = this.updateRateDesignator,
      unknownFields: ByteString = this.unknownFields): GetUpdateRateValueRequest =
      GetUpdateRateValueRequest(updateRateDesignator, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetUpdateRateValueRequest> = object :
        ProtoAdapter<GetUpdateRateValueRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetUpdateRateValueRequest::class, 
      "type.googleapis.com/fedpro.GetUpdateRateValueRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: GetUpdateRateValueRequest): Int {
        var size = value.unknownFields.size
        if (value.updateRateDesignator != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.updateRateDesignator)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetUpdateRateValueRequest) {
        if (value.updateRateDesignator != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.updateRateDesignator)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetUpdateRateValueRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.updateRateDesignator != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.updateRateDesignator)
      }

      override fun decode(reader: ProtoReader): GetUpdateRateValueRequest {
        var updateRateDesignator: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> updateRateDesignator = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetUpdateRateValueRequest(
          updateRateDesignator = updateRateDesignator,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetUpdateRateValueRequest): GetUpdateRateValueRequest =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
