// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.JoinFederationExecutionWithModulesRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import fedpro.type.FomModuleSet
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class JoinFederationExecutionWithModulesRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val federateType: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val federationExecutionName: String = "",
  @field:WireField(
    tag = 3,
    adapter = "fedpro.type.FomModuleSet#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val additionalFomModules: FomModuleSet? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<JoinFederationExecutionWithModulesRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is JoinFederationExecutionWithModulesRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (federateType != other.federateType) return false
    if (federationExecutionName != other.federationExecutionName) return false
    if (additionalFomModules != other.additionalFomModules) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + federateType.hashCode()
      result = result * 37 + federationExecutionName.hashCode()
      result = result * 37 + (additionalFomModules?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """federateType=${sanitize(federateType)}"""
    result += """federationExecutionName=${sanitize(federationExecutionName)}"""
    if (additionalFomModules != null) result += """additionalFomModules=$additionalFomModules"""
    return result.joinToString(prefix = "JoinFederationExecutionWithModulesRequest{", separator =
        ", ", postfix = "}")
  }

  public fun copy(
    federateType: String = this.federateType,
    federationExecutionName: String = this.federationExecutionName,
    additionalFomModules: FomModuleSet? = this.additionalFomModules,
    unknownFields: ByteString = this.unknownFields,
  ): JoinFederationExecutionWithModulesRequest =
      JoinFederationExecutionWithModulesRequest(federateType, federationExecutionName,
      additionalFomModules, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<JoinFederationExecutionWithModulesRequest> = object :
        ProtoAdapter<JoinFederationExecutionWithModulesRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      JoinFederationExecutionWithModulesRequest::class, 
      "type.googleapis.com/fedpro.JoinFederationExecutionWithModulesRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: JoinFederationExecutionWithModulesRequest): Int {
        var size = value.unknownFields.size
        if (value.federateType != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.federateType)
        if (value.federationExecutionName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.federationExecutionName)
        if (value.additionalFomModules != null) size += FomModuleSet.ADAPTER.encodedSizeWithTag(3,
            value.additionalFomModules)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: JoinFederationExecutionWithModulesRequest) {
        if (value.federateType != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.federateType)
        if (value.federationExecutionName != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.federationExecutionName)
        if (value.additionalFomModules != null) FomModuleSet.ADAPTER.encodeWithTag(writer, 3,
            value.additionalFomModules)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter,
          `value`: JoinFederationExecutionWithModulesRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.additionalFomModules != null) FomModuleSet.ADAPTER.encodeWithTag(writer, 3,
            value.additionalFomModules)
        if (value.federationExecutionName != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.federationExecutionName)
        if (value.federateType != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.federateType)
      }

      override fun decode(reader: ProtoReader): JoinFederationExecutionWithModulesRequest {
        var federateType: String = ""
        var federationExecutionName: String = ""
        var additionalFomModules: FomModuleSet? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> federateType = ProtoAdapter.STRING.decode(reader)
            2 -> federationExecutionName = ProtoAdapter.STRING.decode(reader)
            3 -> additionalFomModules = FomModuleSet.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return JoinFederationExecutionWithModulesRequest(
          federateType = federateType,
          federationExecutionName = federationExecutionName,
          additionalFomModules = additionalFomModules,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: JoinFederationExecutionWithModulesRequest):
          JoinFederationExecutionWithModulesRequest = value.copy(
        additionalFomModules = value.additionalFomModules?.let(FomModuleSet.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
