// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.NormalizeObjectInstanceHandleRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.ObjectInstanceHandle
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class NormalizeObjectInstanceHandleRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.ObjectInstanceHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val objectInstanceHandle: ObjectInstanceHandle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NormalizeObjectInstanceHandleRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NormalizeObjectInstanceHandleRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (objectInstanceHandle != other.objectInstanceHandle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (objectInstanceHandle?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (objectInstanceHandle != null) result += """objectInstanceHandle=$objectInstanceHandle"""
    return result.joinToString(prefix = "NormalizeObjectInstanceHandleRequest{", separator = ", ",
        postfix = "}")
  }

  public fun copy(objectInstanceHandle: ObjectInstanceHandle? = this.objectInstanceHandle,
      unknownFields: ByteString = this.unknownFields): NormalizeObjectInstanceHandleRequest =
      NormalizeObjectInstanceHandleRequest(objectInstanceHandle, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NormalizeObjectInstanceHandleRequest> = object :
        ProtoAdapter<NormalizeObjectInstanceHandleRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      NormalizeObjectInstanceHandleRequest::class, 
      "type.googleapis.com/fedpro.NormalizeObjectInstanceHandleRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: NormalizeObjectInstanceHandleRequest): Int {
        var size = value.unknownFields.size
        if (value.objectInstanceHandle != null) size +=
            ObjectInstanceHandle.ADAPTER.encodedSizeWithTag(1, value.objectInstanceHandle)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NormalizeObjectInstanceHandleRequest) {
        if (value.objectInstanceHandle != null) ObjectInstanceHandle.ADAPTER.encodeWithTag(writer,
            1, value.objectInstanceHandle)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter,
          `value`: NormalizeObjectInstanceHandleRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.objectInstanceHandle != null) ObjectInstanceHandle.ADAPTER.encodeWithTag(writer,
            1, value.objectInstanceHandle)
      }

      override fun decode(reader: ProtoReader): NormalizeObjectInstanceHandleRequest {
        var objectInstanceHandle: ObjectInstanceHandle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> objectInstanceHandle = ObjectInstanceHandle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NormalizeObjectInstanceHandleRequest(
          objectInstanceHandle = objectInstanceHandle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NormalizeObjectInstanceHandleRequest):
          NormalizeObjectInstanceHandleRequest = value.copy(
        objectInstanceHandle =
            value.objectInstanceHandle?.let(ObjectInstanceHandle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
