// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.RegisterObjectInstanceWithNameRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import fedpro.type.ObjectClassHandle
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class RegisterObjectInstanceWithNameRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.ObjectClassHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val theClass: ObjectClassHandle? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val theObjectName: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RegisterObjectInstanceWithNameRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RegisterObjectInstanceWithNameRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (theClass != other.theClass) return false
    if (theObjectName != other.theObjectName) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (theClass?.hashCode() ?: 0)
      result = result * 37 + theObjectName.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (theClass != null) result += """theClass=$theClass"""
    result += """theObjectName=${sanitize(theObjectName)}"""
    return result.joinToString(prefix = "RegisterObjectInstanceWithNameRequest{", separator = ", ",
        postfix = "}")
  }

  public fun copy(
    theClass: ObjectClassHandle? = this.theClass,
    theObjectName: String = this.theObjectName,
    unknownFields: ByteString = this.unknownFields,
  ): RegisterObjectInstanceWithNameRequest = RegisterObjectInstanceWithNameRequest(theClass,
      theObjectName, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RegisterObjectInstanceWithNameRequest> = object :
        ProtoAdapter<RegisterObjectInstanceWithNameRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      RegisterObjectInstanceWithNameRequest::class, 
      "type.googleapis.com/fedpro.RegisterObjectInstanceWithNameRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: RegisterObjectInstanceWithNameRequest): Int {
        var size = value.unknownFields.size
        if (value.theClass != null) size += ObjectClassHandle.ADAPTER.encodedSizeWithTag(1,
            value.theClass)
        if (value.theObjectName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.theObjectName)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RegisterObjectInstanceWithNameRequest) {
        if (value.theClass != null) ObjectClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theClass)
        if (value.theObjectName != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.theObjectName)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter,
          `value`: RegisterObjectInstanceWithNameRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.theObjectName != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.theObjectName)
        if (value.theClass != null) ObjectClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theClass)
      }

      override fun decode(reader: ProtoReader): RegisterObjectInstanceWithNameRequest {
        var theClass: ObjectClassHandle? = null
        var theObjectName: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> theClass = ObjectClassHandle.ADAPTER.decode(reader)
            2 -> theObjectName = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RegisterObjectInstanceWithNameRequest(
          theClass = theClass,
          theObjectName = theObjectName,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RegisterObjectInstanceWithNameRequest):
          RegisterObjectInstanceWithNameRequest = value.copy(
        theClass = value.theClass?.let(ObjectClassHandle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
