// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.ReserveObjectInstanceNameRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class ReserveObjectInstanceNameRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val theObjectName: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ReserveObjectInstanceNameRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ReserveObjectInstanceNameRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (theObjectName != other.theObjectName) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + theObjectName.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """theObjectName=${sanitize(theObjectName)}"""
    return result.joinToString(prefix = "ReserveObjectInstanceNameRequest{", separator = ", ",
        postfix = "}")
  }

  public fun copy(theObjectName: String = this.theObjectName, unknownFields: ByteString =
      this.unknownFields): ReserveObjectInstanceNameRequest =
      ReserveObjectInstanceNameRequest(theObjectName, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ReserveObjectInstanceNameRequest> = object :
        ProtoAdapter<ReserveObjectInstanceNameRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      ReserveObjectInstanceNameRequest::class, 
      "type.googleapis.com/fedpro.ReserveObjectInstanceNameRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: ReserveObjectInstanceNameRequest): Int {
        var size = value.unknownFields.size
        if (value.theObjectName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.theObjectName)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ReserveObjectInstanceNameRequest) {
        if (value.theObjectName != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.theObjectName)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ReserveObjectInstanceNameRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.theObjectName != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.theObjectName)
      }

      override fun decode(reader: ProtoReader): ReserveObjectInstanceNameRequest {
        var theObjectName: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> theObjectName = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ReserveObjectInstanceNameRequest(
          theObjectName = theObjectName,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ReserveObjectInstanceNameRequest):
          ReserveObjectInstanceNameRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
