// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.ResignFederationExecutionRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.ResignAction
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class ResignFederationExecutionRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.ResignAction#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val resignAction: ResignAction = ResignAction.UNCONDITIONALLY_DIVEST_ATTRIBUTES,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ResignFederationExecutionRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ResignFederationExecutionRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (resignAction != other.resignAction) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + resignAction.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """resignAction=$resignAction"""
    return result.joinToString(prefix = "ResignFederationExecutionRequest{", separator = ", ",
        postfix = "}")
  }

  public fun copy(resignAction: ResignAction = this.resignAction, unknownFields: ByteString =
      this.unknownFields): ResignFederationExecutionRequest =
      ResignFederationExecutionRequest(resignAction, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ResignFederationExecutionRequest> = object :
        ProtoAdapter<ResignFederationExecutionRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      ResignFederationExecutionRequest::class, 
      "type.googleapis.com/fedpro.ResignFederationExecutionRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: ResignFederationExecutionRequest): Int {
        var size = value.unknownFields.size
        if (value.resignAction != ResignAction.UNCONDITIONALLY_DIVEST_ATTRIBUTES) size +=
            ResignAction.ADAPTER.encodedSizeWithTag(1, value.resignAction)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ResignFederationExecutionRequest) {
        if (value.resignAction != ResignAction.UNCONDITIONALLY_DIVEST_ATTRIBUTES)
            ResignAction.ADAPTER.encodeWithTag(writer, 1, value.resignAction)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ResignFederationExecutionRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.resignAction != ResignAction.UNCONDITIONALLY_DIVEST_ATTRIBUTES)
            ResignAction.ADAPTER.encodeWithTag(writer, 1, value.resignAction)
      }

      override fun decode(reader: ProtoReader): ResignFederationExecutionRequest {
        var resignAction: ResignAction = ResignAction.UNCONDITIONALLY_DIVEST_ATTRIBUTES
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              resignAction = ResignAction.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return ResignFederationExecutionRequest(
          resignAction = resignAction,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ResignFederationExecutionRequest):
          ResignFederationExecutionRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
