// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.SetRangeBoundsRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.DimensionHandle
import fedpro.type.RangeBounds
import fedpro.type.RegionHandle
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class SetRangeBoundsRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.RegionHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val region: RegionHandle? = null,
  @field:WireField(
    tag = 2,
    adapter = "fedpro.type.DimensionHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val dimension: DimensionHandle? = null,
  @field:WireField(
    tag = 3,
    adapter = "fedpro.type.RangeBounds#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val bounds: RangeBounds? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SetRangeBoundsRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetRangeBoundsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (region != other.region) return false
    if (dimension != other.dimension) return false
    if (bounds != other.bounds) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (region?.hashCode() ?: 0)
      result = result * 37 + (dimension?.hashCode() ?: 0)
      result = result * 37 + (bounds?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (region != null) result += """region=$region"""
    if (dimension != null) result += """dimension=$dimension"""
    if (bounds != null) result += """bounds=$bounds"""
    return result.joinToString(prefix = "SetRangeBoundsRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    region: RegionHandle? = this.region,
    dimension: DimensionHandle? = this.dimension,
    bounds: RangeBounds? = this.bounds,
    unknownFields: ByteString = this.unknownFields,
  ): SetRangeBoundsRequest = SetRangeBoundsRequest(region, dimension, bounds, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SetRangeBoundsRequest> = object :
        ProtoAdapter<SetRangeBoundsRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetRangeBoundsRequest::class, 
      "type.googleapis.com/fedpro.SetRangeBoundsRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: SetRangeBoundsRequest): Int {
        var size = value.unknownFields.size
        if (value.region != null) size += RegionHandle.ADAPTER.encodedSizeWithTag(1, value.region)
        if (value.dimension != null) size += DimensionHandle.ADAPTER.encodedSizeWithTag(2,
            value.dimension)
        if (value.bounds != null) size += RangeBounds.ADAPTER.encodedSizeWithTag(3, value.bounds)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetRangeBoundsRequest) {
        if (value.region != null) RegionHandle.ADAPTER.encodeWithTag(writer, 1, value.region)
        if (value.dimension != null) DimensionHandle.ADAPTER.encodeWithTag(writer, 2,
            value.dimension)
        if (value.bounds != null) RangeBounds.ADAPTER.encodeWithTag(writer, 3, value.bounds)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetRangeBoundsRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.bounds != null) RangeBounds.ADAPTER.encodeWithTag(writer, 3, value.bounds)
        if (value.dimension != null) DimensionHandle.ADAPTER.encodeWithTag(writer, 2,
            value.dimension)
        if (value.region != null) RegionHandle.ADAPTER.encodeWithTag(writer, 1, value.region)
      }

      override fun decode(reader: ProtoReader): SetRangeBoundsRequest {
        var region: RegionHandle? = null
        var dimension: DimensionHandle? = null
        var bounds: RangeBounds? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> region = RegionHandle.ADAPTER.decode(reader)
            2 -> dimension = DimensionHandle.ADAPTER.decode(reader)
            3 -> bounds = RangeBounds.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SetRangeBoundsRequest(
          region = region,
          dimension = dimension,
          bounds = bounds,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SetRangeBoundsRequest): SetRangeBoundsRequest = value.copy(
        region = value.region?.let(RegionHandle.ADAPTER::redact),
        dimension = value.dimension?.let(DimensionHandle.ADAPTER::redact),
        bounds = value.bounds?.let(RangeBounds.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
