// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.SubscribeInteractionClassRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.InteractionClassHandle
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class SubscribeInteractionClassRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.InteractionClassHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val theClass: InteractionClassHandle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SubscribeInteractionClassRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SubscribeInteractionClassRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (theClass != other.theClass) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (theClass?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (theClass != null) result += """theClass=$theClass"""
    return result.joinToString(prefix = "SubscribeInteractionClassRequest{", separator = ", ",
        postfix = "}")
  }

  public fun copy(theClass: InteractionClassHandle? = this.theClass, unknownFields: ByteString =
      this.unknownFields): SubscribeInteractionClassRequest =
      SubscribeInteractionClassRequest(theClass, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SubscribeInteractionClassRequest> = object :
        ProtoAdapter<SubscribeInteractionClassRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      SubscribeInteractionClassRequest::class, 
      "type.googleapis.com/fedpro.SubscribeInteractionClassRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: SubscribeInteractionClassRequest): Int {
        var size = value.unknownFields.size
        if (value.theClass != null) size += InteractionClassHandle.ADAPTER.encodedSizeWithTag(1,
            value.theClass)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SubscribeInteractionClassRequest) {
        if (value.theClass != null) InteractionClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theClass)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SubscribeInteractionClassRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.theClass != null) InteractionClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theClass)
      }

      override fun decode(reader: ProtoReader): SubscribeInteractionClassRequest {
        var theClass: InteractionClassHandle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> theClass = InteractionClassHandle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SubscribeInteractionClassRequest(
          theClass = theClass,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SubscribeInteractionClassRequest):
          SubscribeInteractionClassRequest = value.copy(
        theClass = value.theClass?.let(InteractionClassHandle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
