// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.TimeAdvanceRequestRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.LogicalTime
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class TimeAdvanceRequestRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.LogicalTime#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val theTime: LogicalTime? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TimeAdvanceRequestRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TimeAdvanceRequestRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (theTime != other.theTime) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (theTime?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (theTime != null) result += """theTime=$theTime"""
    return result.joinToString(prefix = "TimeAdvanceRequestRequest{", separator = ", ", postfix =
        "}")
  }

  public fun copy(theTime: LogicalTime? = this.theTime, unknownFields: ByteString =
      this.unknownFields): TimeAdvanceRequestRequest = TimeAdvanceRequestRequest(theTime,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TimeAdvanceRequestRequest> = object :
        ProtoAdapter<TimeAdvanceRequestRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      TimeAdvanceRequestRequest::class, 
      "type.googleapis.com/fedpro.TimeAdvanceRequestRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: TimeAdvanceRequestRequest): Int {
        var size = value.unknownFields.size
        if (value.theTime != null) size += LogicalTime.ADAPTER.encodedSizeWithTag(1, value.theTime)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TimeAdvanceRequestRequest) {
        if (value.theTime != null) LogicalTime.ADAPTER.encodeWithTag(writer, 1, value.theTime)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TimeAdvanceRequestRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.theTime != null) LogicalTime.ADAPTER.encodeWithTag(writer, 1, value.theTime)
      }

      override fun decode(reader: ProtoReader): TimeAdvanceRequestRequest {
        var theTime: LogicalTime? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> theTime = LogicalTime.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TimeAdvanceRequestRequest(
          theTime = theTime,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TimeAdvanceRequestRequest): TimeAdvanceRequestRequest =
          value.copy(
        theTime = value.theTime?.let(LogicalTime.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
