// Code generated by Wire protocol buffer compiler, do not edit.
// Source: fedpro.UnsubscribeInteractionClassWithRegionsRequest in RtiAmbassador.proto
package fedpro.call

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import fedpro.type.InteractionClassHandle
import fedpro.type.RegionHandleSet
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class UnsubscribeInteractionClassWithRegionsRequest(
  @field:WireField(
    tag = 1,
    adapter = "fedpro.type.InteractionClassHandle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val theClass: InteractionClassHandle? = null,
  @field:WireField(
    tag = 2,
    adapter = "fedpro.type.RegionHandleSet#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val regions: RegionHandleSet? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UnsubscribeInteractionClassWithRegionsRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UnsubscribeInteractionClassWithRegionsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (theClass != other.theClass) return false
    if (regions != other.regions) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (theClass?.hashCode() ?: 0)
      result = result * 37 + (regions?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (theClass != null) result += """theClass=$theClass"""
    if (regions != null) result += """regions=$regions"""
    return result.joinToString(prefix = "UnsubscribeInteractionClassWithRegionsRequest{", separator
        = ", ", postfix = "}")
  }

  public fun copy(
    theClass: InteractionClassHandle? = this.theClass,
    regions: RegionHandleSet? = this.regions,
    unknownFields: ByteString = this.unknownFields,
  ): UnsubscribeInteractionClassWithRegionsRequest =
      UnsubscribeInteractionClassWithRegionsRequest(theClass, regions, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UnsubscribeInteractionClassWithRegionsRequest> = object :
        ProtoAdapter<UnsubscribeInteractionClassWithRegionsRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      UnsubscribeInteractionClassWithRegionsRequest::class, 
      "type.googleapis.com/fedpro.UnsubscribeInteractionClassWithRegionsRequest", 
      PROTO_3, 
      null, 
      "RtiAmbassador.proto"
    ) {
      override fun encodedSize(`value`: UnsubscribeInteractionClassWithRegionsRequest): Int {
        var size = value.unknownFields.size
        if (value.theClass != null) size += InteractionClassHandle.ADAPTER.encodedSizeWithTag(1,
            value.theClass)
        if (value.regions != null) size += RegionHandleSet.ADAPTER.encodedSizeWithTag(2,
            value.regions)
        return size
      }

      override fun encode(writer: ProtoWriter,
          `value`: UnsubscribeInteractionClassWithRegionsRequest) {
        if (value.theClass != null) InteractionClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theClass)
        if (value.regions != null) RegionHandleSet.ADAPTER.encodeWithTag(writer, 2, value.regions)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter,
          `value`: UnsubscribeInteractionClassWithRegionsRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.regions != null) RegionHandleSet.ADAPTER.encodeWithTag(writer, 2, value.regions)
        if (value.theClass != null) InteractionClassHandle.ADAPTER.encodeWithTag(writer, 1,
            value.theClass)
      }

      override fun decode(reader: ProtoReader): UnsubscribeInteractionClassWithRegionsRequest {
        var theClass: InteractionClassHandle? = null
        var regions: RegionHandleSet? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> theClass = InteractionClassHandle.ADAPTER.decode(reader)
            2 -> regions = RegionHandleSet.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UnsubscribeInteractionClassWithRegionsRequest(
          theClass = theClass,
          regions = regions,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UnsubscribeInteractionClassWithRegionsRequest):
          UnsubscribeInteractionClassWithRegionsRequest = value.copy(
        theClass = value.theClass?.let(InteractionClassHandle.ADAPTER::redact),
        regions = value.regions?.let(RegionHandleSet.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
